highlighter: rouge
permalink: none

exclude: [LICENSE, local.sh, docker.sh, Rakefile, Gemfile, Gemfile.lock, README.md, vendor]

kramdown:
  input: GFM
  hard_wrap: false

repository: baiyuNinja/baiyuNinja.github.io

plugins:
  - jemoji
  - jekyll-redirect-from
  - jekyll-seo-tag

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      permalink: /blog/:year/:month/:day/:title/

title: 1024bit

description: 

url: https://blog.1024bit.io

author: baiyuNinja

username: baiyuNinja

social:
  name: baiyuNinja
  wechat: https://1024bit.cn-bj.ufileos.com/blog%2FWeChat.JPG
  telegram: https://github.com/baiyuNinja

info-url:
  github: https://github.com/baiyuNinja
  email: admin@1024bit.io
  domain: https://github.com/baiyuNinja

cdn-url:
  jquery-min: https://1024bit.cn-bj.ufileos.com/blog%2Fstatic%2Fjquery.min.js
  toc-js: https://1024bit.cn-bj.ufileos.com/blog%2Fstatic%2Ftoc.js
  css: https://1024bit.cn-bj.ufileos.com/blog%2Fstatic%2Fstyle.css
  logo: https://1024bit.cn-bj.ufileos.com/blog%2Fimages%2Fcat%2Fcat.png
  fav: https://1024bit.cn-bj.ufileos.com/blog%2Fimages%2Fcat%2Ffav.png

string:
  first-year: 2017
  home-name: ğŸ­
  index: ä¸€è·¯å°‹å°‹è¦“è¦“ é‚£ä½•æ›¾æœ‰éæ”¾æ£„
  # projects: å¯¦ç¿’ / é …ç›® / <a href="https://1024bit.cn-bj.ufileos.com/blog%2Fresume.pdf" target="_blank">æˆ‘çš„ç°¡æ­·</a>
  projects: å¯¦ç¿’ / é …ç›®
  blog: ğŸ” <a href="/blog/categories.html">åˆ†é¡</a>
  about: Hello it's me ~
  copyright: baiyuNinja
