highlighter: rouge
permalink: none
exclude: [LICENSE, local.sh, docker.sh, Rakefile, Gemfile, Gemfile.lock, README.md, vendor]
kramdown:
  input: GFM
  hard_wrap: false
repository: baiyuNinja/baiyuNinja.github.io
plugins:
  - jemoji
  # - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-seo-tag
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      permalink: /blog/:year/:month/:day/:title/
title: 1024bit
description: 
url: https://blog.1024bit.io
author: baiyuNinja
twitter:
username: baiyuNinja

social:
  name: baiyuNinja
  links:

cdn-url:
  logo: /images/contents/cat.png

string:
  home-name: ğŸ­
  index: ä¸€è·¯å°‹å°‹è¦“è¦“ é‚£ä½•æ›¾æœ‰éæ”¾æ£„
  projects: å¯¦ç¿’ / é …ç›®
  blog: ğŸ” <a href="/blog/categories.html">åˆ†é¡</a>
  about: Hello it's me ~